name: STREETSPACE_DOCS

channels:
  - defaults
  - conda-forge

dependencies:
  - python=3
  - descartes
  - geopandas
  - matplotlib
  - networkx
  - numpy
  - pandas
  - requests
  - Rtree
  - Shapely
  - osmnx